# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


mysql:
  repository: mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5.6"  

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

mysql1:        
  type: NodePort
  port: 3306   

